### ISSUE TITLE
How does this tool fit into a development flow?

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/vidx2pidx#7]
Not sure what the purpose of 'vidx2pidx' is.  When should I use this tool?  Is this something that should be used in context with cpackget?

**Comment by jkrech** [comment]
This tool does what today is e.g. done by the Keil.com server.
It reads www.keil.com/pack/Keil.vidx and creates www.keil.com/pack/index.pidx
A user could create an index.pidx from a subset of pack vendors by describing their own vidx file which may also point to none-public locations (internally hosted packs).
